name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # Only trigger when files in backend directory change

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
